debug:
  enable: true

  level:
    info:
      enable: true
      prefix: '[Debug] '
    warn:
      enable: true
      prefix: '[Debug] '
    error:
      enable: true
      prefix: '[Debug] '

limits:
  give: 64
  take: 64

modules:
  # если вам нужно включить или выключить все модули, то раскомментируйте строку ниже и установите значение true или false
  # all: true
  folder: true
  time-format: true

economy:
  enable: false
  provider: Vault # Vault, VaultUnlocked, PlayerPoints
