name: LastItems
version: '0.2.4'

dependencies:
  server:
    BLib:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false

main: ru.last.lastitems.LastItemsFree
api-version: '1.19'
author: Last

description: "Плагин для кастомных предметов на 1.16.5 - 26.1.2"
website: "https://wiki.laststudio.space/lastitems"