name: LastItems
version: '0.2.5-BETA'

depend: [ BLib ]
softdepend: [ PlaceholderAPI, LastMines ]

main: ru.last.lastitems.LastItemsFree
api-version: "1.16"
author: Last

description: "Плагин для кастомных предметов на 1.16.5 - 26.1.2"
website: "https://wiki.laststudio.space/lastitems"